name: Flutter Build v1.0

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'
          channel: 'stable'

      # 3️⃣ Install dependencies with logging
      - name: Install dependencies (pub get)
        run: |
          echo "=== PUB GET LOG START ==="
          flutter pub get 2>&1 | tee flutter_pub_get_log.txt
          echo "=== PUB GET LOG END ==="

      # 4️⃣ Build APK with full logging and non-fatal warning handling
      - name: Build APK (release)
        run: |
          echo "=== BUILD LOG START ==="
          set +e  # continue on non-fatal errors
          flutter build apk --release 2>&1 | tee flutter_build_log.txt
          set -e  # stop on fatal errors
          echo "=== BUILD LOG END ==="
          # Rename APK with commit hash
          COMMIT_HASH=$(git rev-parse --short HEAD)
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-release-$COMMIT_HASH.apk

      # 5️⃣ Upload logs as artifacts
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            flutter_pub_get_log.txt
            flutter_build_log.txt

      # 6️⃣ Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: qwikqr-apk
          path: build/app/outputs/flutter-apk/app-release-*.apk
