name: Flutter Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Install dependencies
        run: flutter pub get 2>&1 | tee flutter_pub_get_log.txt

      - name: Build APK
        run: flutter build apk --release 2>&1 | tee flutter_build_log.txt

      - name: Rename APK with commit hash and run number
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          RUN_NUMBER=${{ github.run_number }}
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-release-${COMMIT_HASH}-${RUN_NUMBER}.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: qwikqr-apk
          path: build/app/outputs/flutter-apk/app-release-*.apk

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            flutter_pub_get_log.txt
            flutter_build_log.txt
